SpaceX.API.Device.Request is a message:
message Request {
  uint64 id = 1;
  string target_id = 13;
  uint64 epoch_id = 14;
  oneof request {
    .SpaceX.API.Device.SignedData signed_request = 15;
    .SpaceX.API.Device.RebootRequest reboot = 1001;
    .SpaceX.API.Device.SpeedTestRequest speed_test = 1003;
    .SpaceX.API.Device.GetStatusRequest get_status = 1004;
    .SpaceX.API.Device.AuthenticateRequest authenticate = 1005;
    .SpaceX.API.Device.GetNextIdRequest get_next_id = 1006;
    .SpaceX.API.Device.GetHistoryRequest get_history = 1007;
    .SpaceX.API.Device.GetDeviceInfoRequest get_device_info = 1008;
    .SpaceX.API.Device.GetPingRequest get_ping = 1009;
    .SpaceX.API.Device.SetTrustedKeysRequest set_trusted_keys = 1010;
    .SpaceX.API.Device.FactoryResetRequest factory_reset = 1011;
    .SpaceX.API.Device.GetLogRequest get_log = 1012;
    .SpaceX.API.Device.SetSkuRequest set_sku = 1013;
    .SpaceX.API.Device.UpdateRequest update = 1014;
    .SpaceX.API.Device.GetNetworkInterfacesRequest get_network_interfaces = 1015;
    .SpaceX.API.Device.PingHostRequest ping_host = 1016;
    .SpaceX.API.Device.GetLocationRequest get_location = 1017;
    .SpaceX.API.Device.GetHeapDumpRequest get_heap_dump = 1019;
    .SpaceX.API.Device.RestartControlRequest restart_control = 1020;
    .SpaceX.API.Device.FuseRequest fuse = 1021;
    .SpaceX.API.Device.GetPersistentStatsRequest get_persistent_stats = 1022;
    .SpaceX.API.Device.GetConnectionsRequest get_connections = 1023 [deprecated = true];
    .SpaceX.API.Device.StartSpeedtestRequest start_speedtest = 1027;
    .SpaceX.API.Device.GetSpeedtestStatusRequest get_speedtest_status = 1028;
    .SpaceX.API.Device.ReportClientSpeedtestRequest report_client_speedtest = 1029;
    .SpaceX.API.Device.InitiateRemoteSshRequest initiate_remote_ssh = 1030 [deprecated = true];
    .SpaceX.API.Device.SelfTestRequest self_test = 1031;
    .SpaceX.API.Device.SetTestModeRequest set_test_mode = 1032;
    .SpaceX.API.Device.SoftwareUpdateRequest software_update = 1033;
    .SpaceX.API.Device.EnableDebugTelemRequest enable_debug_telem = 1034;
    .SpaceX.API.Device.IQCaptureRequest iq_capture = 1035;
    .SpaceX.API.Device.GetRadioStatsRequest get_radio_stats = 1036;
    .SpaceX.API.Device.GetTimeRequest time = 1037;
    .SpaceX.API.Device.RunIperfServerRequest run_iperf_server = 1038;
    .SpaceX.API.Device.TcpConnectivityTestRequest tcp_connectivity_test = 1039;
    .SpaceX.API.Device.UdpConnectivityTestRequest udp_connectivity_test = 1040;
    .SpaceX.API.Device.GetGoroutineStackTracesRequest get_goroutine_stack_traces = 1041;
    .SpaceX.API.Device.SignedData sensitive_request = 1078;
    .SpaceX.API.Device.DishStowRequest dish_stow = 2002;
    .SpaceX.API.Device.DishGetContextRequest dish_get_context = 2003;
    .SpaceX.API.Device.DishSetEmcRequest dish_set_emc = 2007;
    .SpaceX.API.Device.DishGetObstructionMapRequest dish_get_obstruction_map = 2008;
    .SpaceX.API.Device.DishGetEmcRequest dish_get_emc = 2009;
    .SpaceX.API.Device.DishSetConfigRequest dish_set_config = 2010;
    .SpaceX.API.Device.DishGetConfigRequest dish_get_config = 2011;
    .SpaceX.API.Device.DishPowerSaveRequest dish_power_save = 2013;
    .SpaceX.API.Device.DishInhibitGpsRequest dish_inhibit_gps = 2014;
    .SpaceX.API.Device.DishGetDataRequest dish_get_data = 2015;
    .SpaceX.API.Device.DishClearObstructionMapRequest dish_clear_obstruction_map = 2017;
    .SpaceX.API.Device.DishSetMaxPowerTestModeRequest dish_set_max_power_test_mode = 2018;
    .SpaceX.API.Device.DishActivateRssiScanRequest dish_activate_rssi_scan = 2019;
    .SpaceX.API.Device.DishGetRssiScanResultRequest dish_get_rssi_scan_result = 2020;
    .SpaceX.API.Device.DishFactoryResetRequest dish_factory_reset = 2021;
    .SpaceX.API.Device.ResetButtonRequest reset_button = 2022;
    .SpaceX.API.Device.SoftwareUpdateRequest set_per_vehicle_config = 2023;
    .SpaceX.API.Device.DishAviationTestRequest dish_aviation_test = 2024;
    .SpaceX.API.Device.DishInhibitRfRequest dish_inhibit_rf = 2026;
    .SpaceX.API.Device.ZtlmQueryRequest ztlm_query = 2027;
    .SpaceX.API.Device.DishStartTestModeServerRequest dish_start_test_mode_server = 2028;
    .SpaceX.API.Device.UserReportedIssueRequest user_reported_issue = 2029;
    .SpaceX.API.Device.WifiSetConfigRequest wifi_set_config = 3001;
    .SpaceX.API.Device.WifiGetClientsRequest wifi_get_clients = 3002;
    .SpaceX.API.Device.WifiSetupRequest wifi_setup = 3003;
    .SpaceX.API.Device.WifiGetPingMetricsRequest wifi_get_ping_metrics = 3007;
    .SpaceX.API.Device.WifiGetConfigRequest wifi_get_config = 3009;
    .SpaceX.API.Device.WifiSetMeshDeviceTrustRequest wifi_set_mesh_device_trust = 3012;
    .SpaceX.API.Device.WifiSetMeshConfigRequest wifi_set_mesh_config = 3013 [deprecated = true];
    .SpaceX.API.Device.WifiGetClientHistoryRequest wifi_get_client_history = 3015;
    .SpaceX.API.Device.WifiSetAviationConformedRequest wifi_set_aviation_conformed = 3016;
    .SpaceX.API.Device.WifiSetClientGivenNameRequest wifi_set_client_given_name = 3017;
    .SpaceX.API.Device.WifiSelfTestRequest wifi_self_test = 3018;
    .SpaceX.API.Device.WifiCalibrationModeRequest wifi_calibration_mode = 3019;
    .SpaceX.API.Device.WifiGuestInfoRequest wifi_guest_info = 3020;
    .SpaceX.API.Device.WifiRfTestRequest wifi_rf_test = 3021;
    .SpaceX.API.Device.WifiGetFirewallRequest wifi_get_firewall = 3024;
    .SpaceX.API.Device.WifiTogglePoeNegotiationRequest wifi_toggle_poe_negotiation = 3025;
    .SpaceX.API.Device.WifiFactoryTestCommandRequest wifi_factory_test_command = 3026;
    .SpaceX.API.Device.WifiStartLocalTelemProxyRequest wifi_start_local_telem_proxy = 3027;
    .SpaceX.API.Device.WifiRunSelfTestRequest wifi_run_self_test = 3028;
    .SpaceX.API.Device.WifiBackhaulStatsRequest wifi_backhaul_stats = 3029;
    .SpaceX.API.Device.WifiToggleUmbilicalModeRequest wifi_toggle_umbilical_mode = 3030;
    .SpaceX.API.Device.WifiClientSandboxRequest wifi_client_sandbox = 3031;
    .SpaceX.API.Device.WifiRunDebugNetsysRequest wifi_run_debug_netsys = 3032;
    .SpaceX.API.Device.WifiResetEthPhyRequest wifi_reset_eth_phy = 3033;
    .SpaceX.API.Device.WifiFlushHardwareNatRequest wifi_flush_hardware_nat = 3034;
    .SpaceX.API.Device.WifiWriteCalibrationRequest wifi_write_calibration = 3035;
    .SpaceX.API.Device.WifiStartTracerouteRequest wifi_start_traceroute = 3036;
    .SpaceX.API.Device.WifiGetTracerouteStatusRequest wifi_get_traceroute_status = 3037;
    .SpaceX.API.Device.TransceiverIFLoopbackTestRequest transceiver_if_loopback_test = 4001;
    .SpaceX.API.Device.TransceiverGetStatusRequest transceiver_get_status = 4003;
    .SpaceX.API.Device.TransceiverGetTelemetryRequest transceiver_get_telemetry = 4004;
    .SpaceX.API.Device.Services.Unlock.StartUnlockRequest start_unlock = 5000;
    .SpaceX.API.Device.Services.Unlock.FinishUnlockRequest finish_unlock = 5001;
    .SpaceX.API.Device.GetDiagnosticsRequest get_diagnostics = 6000;
    .SpaceX.API.Device.GetGnssMeasurementRequest get_gnss_measurement = 7000;
    .SpaceX.API.Device.ToggleModeRequest toggle_mode = 7001;
  }
  reserved 1018, 1025, 1026, 2012, 2016, 3011, 3014, 3202;
  reserved "start_dish_self_test";
}
