; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secrets.ini
data_dir = data

[common]
build_flags =
    -D WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D WIFI_PASSWORD=\"${secrets.wifi_password}\"
    -D GMAIL_EMAIL=\"${secrets.gmail_email}\"
    -D GMAIL_PASSWORD=\"${secrets.gmail_password}\"

; --- Спільні налаштування ---
[env]
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1

# ESP32-S3 Arduino LVGL WIFI and Bluetooth development board 4.0 inch 480 * 480 
# великий квадратний в корпусі
[env:esp32-4848s040]
upload_port = /dev/ttyUSB0
upload_speed = 921600
platform = espressif32
monitor_filters = esp32_exception_decoder
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    ${common.build_flags}
    -D BOARD_HAS_PSRAM
    -D LGFX_USE_V1
    -D BOARD_4848S040
    -D TFT_BL=38
    -D TFT_ROTATION=2
    -D SPRITE_COLOR_DEPTH=16
    ; -mfix-esp32-psram-cache-issue
    ; -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*> +<../src-4848s040/>
lib_deps = 
    lovyan03/LovyanGFX@^1.1.16
    tamctec/TAMC_GT911@^1.0.2
    dvarrel/ESPping @ ^1.0.5
    ; lvgl/lvgl@^8.3.11
    mobizt/ESP Mail Client @ ^3.4.17
    bodmer/TJpg_Decoder
    bblanchon/ArduinoJson

# ST7789 ESP32 WiFi Bluetooth Development Board 2.8-inch Driver Intelligent Display Color Screen Onboard ESP32-32E Module
# в прозорому корпусі (дві кришки)
[env:esp32-st7789]
upload_port = /dev/ttyUSB1
upload_speed = 921600
; upload_speed = 115200
platform = espressif32
board = esp32dev
board_build.partitions = default.csv
; board_build.partitions = min_spiffs.csv
; board_build.partitions = no_ota.csv # minimal
board_build.filesystem = littlefs
board_build.embed_txtfiles = 
board_upload.flash_size = 4MB
; board_build.data_dir = data-st7789
framework = arduino
build_src_filter = +<*> +<../src-st7789/>
; Force PlatformIO to build in debug mode
; build_type = debug
lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    dvarrel/ESPping @ ^1.0.5
    mobizt/ESP Mail Client @ ^3.4.17
    bodmer/TJpg_Decoder@^1.1.0
    bblanchon/ArduinoJson
build_flags =
    -include include/Setup_ST7789.h
    ${common.build_flags}
    -Os
    -Wl,-Map,firmware.map
    -D CORE_DEBUG_LEVEL=0
    -D USER_SETUP_LOADED=1
    -D BOARD_ST7789=1
    -D ST7789_DRIVER=1
    -D SPRITE_COLOR_DEPTH=8
    -D TFT_ROTATION=3
    -D TFT_INVERSION_OFF=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=1
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D SPI_FREQUENCY=40000000 # 20000000 / 27000000 / 40000000
    -D TFT_RGB_ORDER=TFT_BGR
    -D TOUCH_CS=33
