; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; 
; https://docs.platformio.org/en/stable/projectconf/index.html

[platformio]
extra_configs = secrets.ini
data_dir = data

[common]
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    ; -I lib/EventDispatcher/
    -D PIO_PIOENV=\"${PIOENV}\"
    -D SYSENV_BOARD_VERSION=\"${sysenv.BOARD_VERSION}\"
    -D WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D WIFI_PASSWORD=\"${secrets.wifi_password}\"
    -D GMAIL_EMAIL=\"${secrets.gmail_email}\"
    -D GMAIL_PASSWORD=\"${secrets.gmail_password}\"

# ESP32-S3 (QFN56) - JC3248W535C
# прямоугольний, в чорному корпусі, з дінаміком
# https://spotpear.com/wiki/ESP32-S3-3.5-inch-LCD-Captive-TouchScreen-Display-480x320-Tablet-MP3-Video-Weather-Clock.html
# ffmpeg -i your_video.mp4 -vcodec mjpeg -s 480x320 -r 20 -an boot.mpeg

; --- Спільні налаштування ---
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1
monitor_echo = yes

# ESP32-S3 Arduino LVGL WIFI and Bluetooth development board 4.0 inch 480 * 480 
# великий квадратний в корпусі
[env:esp32-4848s040]
extends = env
upload_port = /dev/ttyUSB0
upload_speed = 921600
monitor_filters = esp32_exception_decoder
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
; board_build.partitions = default.csv
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_unflags = ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -D CONFIG_HEAP_POISONING_COMPREHENSIVE=1
    -D BOARD_HAS_PSRAM
    -D LGFX_USE_V1
    -D BOARD_4848S040

    # esp32-4848s040 - CS=42, SCK=48, MOSI=47, MISO=41
    -D SD_CS=42
    -D SD_MOSI=47
    -D SD_MISO=41
    -D SD_SCK=48
    -D SD_FREQ=4000000

    -D TFT_BL=38
    -D TFT_ROTATION=2
    -D SPRITE_COLOR_DEPTH=16
    ; -mfix-esp32-psram-cache-issue
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    -D BACKGROUND_IMAGES_COUNT=0
    -D LITTLEFS_BACKGROUND_IMAGE=\"/moon-480x480.jpg\"
build_src_filter = +<*> +<../src-4848s040/>
lib_deps = 
    lovyan03/LovyanGFX @ ^1.1.16
    tamctec/TAMC_GT911 @ ^1.0.2
    dvarrel/ESPping @ ^1.0.5
    ; lvgl/lvgl@^8.3.11
    mobizt/ESP Mail Client @ ^3.4.17
    bodmer/TJpg_Decoder
    bblanchon/ArduinoJson
    knolleary/PubSubClient@^2.8

# ST7789 ESP32 WiFi Bluetooth Development Board 2.8-inch Driver Intelligent Display Color Screen Onboard ESP32-32E Module
# в прозорому корпусі (дві кришки)
[env:esp32-st7789]
extends = env
upload_port = /dev/ttyUSB0
upload_speed = 921600
; upload_speed = 115200
board = esp32dev
; board_build.partitions = default.csv
; board_build.partitions = min_spiffs.csv
; board_build.partitions = no_ota.csv # minimal
board_build.partitions = partitions_st7789.csv
; board_upload.offset_address = 0x90000
board_build.filesystem = littlefs
board_build.embed_txtfiles = 
board_upload.flash_size = 4MB
; board_build.data_dir = data-st7789
build_src_filter = +<*> +<../src-st7789/>
; Force PlatformIO to build in debug mode
; build_type = debug
lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    dvarrel/ESPping @ ^1.0.5
    ; mobizt/ESP Mail Client @ ^3.4.17
    bodmer/TJpg_Decoder @ ^1.1.0
    bblanchon/ArduinoJson
    knolleary/PubSubClient @ ^2.8
build_unflags = ${common.build_unflags}
build_flags =
    -include include/Setup_ST7789.h
    ${common.build_flags}
    -Os
    ; -Wl,-Map,${platformio.build_dir}/${this.__env__}/firmware.map
    -Wl,-Map,firmware.map
    ; -D CONFIG_BT_ENABLED=0
    -D CORE_DEBUG_LEVEL=3
    -D USER_SETUP_LOADED=1
    -D BOARD_ST7789=1
    -D ST7789_DRIVER=1

    -D SPRITE_COLOR_DEPTH=8

    -D USE_HSPI_PORT=1      ; принудительно заставляем дисплей использовать 

    -D TFT_ROTATION=3
    -D TFT_INVERSION_OFF=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=1

    # // esp32-st7789 - CS=5, SCK=18, MISO=19, MOSI=23, freq=400000
    -D SD_CS=5
    -D SD_MOSI=23
    -D SD_MISO=19
    -D SD_SCK=18
    ; -D SD_FREQ=400000 # success
    ; -D SD_FREQ=800000 # success
    -D SD_FREQ=400000

    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D SPI_FREQUENCY=40000000 # 20000000 / 27000000 / 40000000
    -D TFT_RGB_ORDER=TFT_BGR
    -D TOUCH_CS=33
    -D LIGHT_SENSOR_PIN=34
    -D BACKGROUND_IMAGES_COUNT=1

